apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nodejs-tinyurl-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nodejs-tinyurl
    spec:
      containers:
        - name: nodejs-tinyurl-pod
          image: abhinavdhasmana/tinyurl
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
